- name: demo-ext-api-apb playbook to unbind the application
  hosts: localhost
  gather_facts: false
  connection: local
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: ansibleplaybookbundle.asb-modules
  - role: unbind-demo-ext-api-apb
    playbook_debug: false