#############################################################################
# An OpenShift persistent volume claim will allow the database to save between
# restarts.
# https://docs.openshift.org/latest/architecture/additional_concepts/storage.html#persistent-volume-claims
#############################################################################
- name: create volumes
  k8s_v1_persistent_volume_claim:
    name: demo-api-db
    namespace: '{{ namespace }}'
    state: present
    access_modes:
      - ReadWriteOnce
    resources_requests:
      storage: 1Gi


#############################################################################
# An OpenShift Origin deployment configuration provides a replication
# controller, spins up pods, and also provides the ability to transition from
# one deployment of an image to a new one.
# https://docs.openshift.org/latest/architecture/core_concepts/deployments.html#deployments-and-deployment-configurations
#############################################################################
- name: create demo-api-db deployment config
  openshift_v1_deployment_config:
    name: demo-api-db
    namespace: '{{ namespace }}'
    labels:
      app: demo-api-db
      service: demo-api-db
    replicas: 1
    selector:
      app: demo-api-db
      service: demo-api-db
    spec_template_metadata_labels:
      app: demo-api-db
      service: demo-api-db
    containers:
    - env:
      - name: POSTGRESQL_PASSWORD
        value: "{{ postgresql_password }}"
      - name: POSTGRESQL_USER
        value: "{{ postgresql_user }}"
      - name: POSTGRESQL_DATABASE
        value: "{{ postgresql_database }}"
      image: docker.io/centos/postgresql-95-centos7
      name: demo-api-db
      ports:
      - container_port: 5432
        protocol: TCP
      termination_message_path: /dev/termination-log
      volume_mounts:
      - mount_path: /var/lib/pgsql/data
        name: demo-api-db
      working_dir: /
    volumes:
    - name: demo-api-db
      persistent_volume_claim:
        claim_name: demo-api-db
      test: false
      triggers:
      - type: ConfigChange

